# Site settings
title: 先用着这个标题                        #你博客的标题
SEOTitle: xieincz的博客 | 先用着这个标题     #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-fish.jpg             #显示在首页的背景图片
email: xieincz@gmail.com
description: "暂时没想到介绍怎么写."   #网站介绍
keyword: " xieincz Blog, xieincz的博客, xieincz, :), Microsoft, Windows, Google, Android"
url: "https://xieincz.github.io"          # your host, for absolute URL # 这个就是填写你的博客地址
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'  # 这个我们不用填写

github_repo: "https://github.com/xieincz/xieincz.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "说点什么好呢?"
sidebar-avatar: /img/about-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`   # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g



# SNS settings
RSS: false
# weibo_username:     null
#zhihu_username:     null
#github_username:    null
#facebook_username:  null
#jianshu_username:   jianshu_id
#twitter_username:   null




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 33031c7fcdd83693bbc1                            #生成的clientID
  clientSecret: a99052ca067813e86f7fec99a8daad2554cb1dc3    #生成的clientSecret
  repo: xieincz.github.io    #仓库名称
  owner: xieincz    #github用户名
  admin: xieincz
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 4c8f171838d14cdfd132d95c1b743a72

# Google Analytics
ga_track_id: 'UA-123877368-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    },{
        title: "简书",
        href: "http://www.jianshu.com"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com"
    }
]
